"""create inital tables

Revision ID: aa63cdcf5a83
Revises: 778bc6cba949
Create Date: 2023-05-19 14:51:42.858795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa63cdcf5a83'
down_revision = '778bc6cba949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###
